import os

def print_banner():
    banner = """
    ╔════════════════════════════════════════════════════╗
    ║      USB Rubber Ducky Payload Generator             ║
    ║      Coded by Pakistani Ethical Hacker              ║
    ║            Mr Sabaz Ali Khan                       ║
    ╚════════════════════════════════════════════════════╝
    """
    print(banner)

def generate_payload(payload_type, content, output_file):
    with open(output_file, 'w') as f:
        f.write("REM USB Rubber Ducky Payload Generated by Mr Sabaz Ali Khan\n")
        f.write("DELAY 1000\n")
        
        if payload_type == "string":
            f.write(f"STRING {content}\n")
            f.write("ENTER\n")
        elif payload_type == "cmd":
            f.write("GUI r\n")
            f.write("DELAY 500\n")
            f.write("STRING cmd\n")
            f.write("ENTER\n")
            f.write("DELAY 1000\n")
            f.write(f"STRING {content}\n")
            f.write("ENTER\n")
        
        f.write("DELAY 500\n")

def main():
    print_banner()
    print("Select Payload Type:")
    print("1. Type a string")
    print("2. Open CMD and execute command")
    
    choice = input("Enter choice (1 or 2): ")
    
    if choice not in ['1', '2']:
        print("Invalid choice! Exiting...")
        return
    
    content = input("Enter the string or command to execute: ")
    output_file = input("Enter output file name (e.g., payload.txt): ")
    
    payload_type = "string" if choice == '1' else "cmd"
    
    try:
        generate_payload(payload_type, content, output_file)
        print(f"Payload generated successfully and saved to {output_file}")
    except Exception as e:
        print(f"Error generating payload: {e}")

if __name__ == "__main__":
    main()